spring.application.name=backend-auth
# Run this mini-project on port 8080
server.port=8080

# Database Configuration (Make sure your MySQL server is running!)
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=YOUR_MYSQL_PASSWORD_HERE

# Hibernate JPA settings to auto-create database tables
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect